# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-18 08:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('table', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='row',
            options={'ordering': ('-created',)},
        ),
        migrations.AddField(
            model_name='row',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cell',
            name='content',
            field=models.CharField(max_length=100),
        ),
    ]
